services:
  - type: web
    name: totem-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3333
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-lingering-paper-adck7igg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_8ILmFPEdxr5J
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
